[package]
name = "rukkit-world"
description = "Chunk storage, paletted containers and world generation for Rukkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bytes = "1.12.1"
flate2 = "1.1.10"
rukkit-protocol.workspace = true
thiserror = "2.0.20"
tracing = "0.1.44"

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }
rand = "0.9.5"

[[bench]]
name = "chunk"
harness = false
